services:
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - NODE_ENV=development
      - DATABASE_FILE=/data/db.sqlite
      - ENABLE_TEST_ROUTES=${ENABLE_TEST_ROUTES:-false}
    volumes:
      - backend_data:/data
      - backend_node_modules:/usr/src/app/node_modules
    ports:
      - "3333:3333"   # <--- backend disponÃ­vel localmente
    restart: unless-stopped

volumes:
  backend_data:
  backend_node_modules:
